services:
#    boletus.example:
#        class: BoletusBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    boletus.subscriber.caja:
        class: BoletusBundle\Service\CajaSubscriber
        tags:
            - {name: doctrine.event_subscriber }